var searchData=
[
  ['xadc',['XADC',['../group__x_a_d_c.html',1,'']]],
  ['xadc_20data_20resolution',['xADC Data Resolution',['../group__x_a_d_c___data___resolution.html',1,'']]],
  ['xadc_20interrupt_20event',['xADC Interrupt Event',['../group__x_a_d_c___events.html',1,'']]],
  ['xadc_20api',['xADC API',['../group__x_a_d_c___exported___a_p_is.html',1,'']]],
  ['xadc_20external_20tigger_20source_20mode',['xADC External Tigger Source Mode',['../group__x_a_d_c___e_x_t___trigger___mode.html',1,'']]],
  ['xadc_20interrupt_20source',['xADC Interrupt Source',['../group__x_a_d_c___ints.html',1,'']]],
  ['xadc_20operation_20mode',['xADC Operation Mode',['../group__x_a_d_c___mode.html',1,'']]],
  ['xadc_20step_20config',['xADC Step Config',['../group__x_a_d_c___step___config.html',1,'']]],
  ['xadc_20trigger_20source',['xADC Trigger Source',['../group__x_a_d_c___trigger___source.html',1,'']]],
  ['xcore',['XCORE',['../group__x_c_o_r_e.html',1,'']]],
  ['xcore_5fexported_5fapis',['XCORE_Exported_APIs',['../group__x_c_o_r_e___exported___a_p_is.html',1,'']]],
  ['xcore_5fexported_5fmacros',['XCORE_Exported_Macros',['../group__x_c_o_r_e___exported___macros.html',1,'']]],
  ['xdebug',['XDebug',['../group__x_debug.html',1,'']]],
  ['xdebug_20api',['xDebug API',['../group__x_debug___exported___a_p_is.html',1,'']]],
  ['xgpio',['XGPIO',['../group__x_g_p_i_o.html',1,'']]],
  ['xgpio_20interrupt_20number_20config',['xGPIO interrupt number config',['../group__x_g_p_i_o___config.html',1,'']]],
  ['xgpio_20dir_20mode',['xGPIO Dir Mode',['../group__x_g_p_i_o___dir___mode.html',1,'']]],
  ['xgpio_20api',['xGPIO API',['../group__x_g_p_i_o___exported___a_p_is.html',1,'']]],
  ['xgpio_20general_20pin_20id',['xGPIO General Pin ID',['../group__x_g_p_i_o___general___pin___i_ds.html',1,'']]],
  ['xgpio_20general_20purpose_20short_20pin',['xGPIO General Purpose Short Pin',['../group__x_g_p_i_o___g_p___short___pin.html',1,'']]],
  ['xgpio_20int_20type',['xGPIO Int Type',['../group__x_g_p_i_o___int___type.html',1,'']]],
  ['xgpio_20pad_20config_20strength',['xGPIO Pad Config Strength',['../group__x_g_p_i_o___pad___config___strength.html',1,'']]],
  ['xgpio_20general_20peripheral_20pin',['xGPIO General Peripheral Pin',['../group__x_g_p_i_o___peripheral___pin.html',1,'']]],
  ['xgpio_20short_20pin_20id',['xGPIO Short Pin ID',['../group__x_g_p_i_o___short___pin.html',1,'']]],
  ['xi2c',['XI2C',['../group__x_i2_c.html',1,'']]],
  ['xi2c_20master_20event',['xI2C Master Event',['../group__x_i2_c___event___master.html',1,'']]],
  ['xi2c_20slave_20event',['xI2C Slave Event',['../group__x_i2_c___event___slave.html',1,'']]],
  ['xi2c_20api',['xI2C API',['../group__x_i2_c___exported___a_p_is.html',1,'']]],
  ['xi2c_20general_20call',['xI2C General Call',['../group__x_i2_c___general___call.html',1,'']]],
  ['xi2c_20master_20interrupt',['xI2C Master Interrupt',['../group__x_i2_c___i_n_t___master.html',1,'']]],
  ['xi2c_20slave_20interrupt',['xI2C Slave Interrupt',['../group__x_i2_c___i_n_t___slave.html',1,'']]],
  ['xi2c_20master_20error',['xI2C Master Error',['../group__x_i2_c___master___error.html',1,'']]],
  ['xlowlayer',['XLowLayer',['../group__x_low_layer.html',1,'']]],
  ['xlowlayer_20types',['xLowLayer Types',['../group__x_low_layer___exported___types.html',1,'']]],
  ['xlowlayer_20hardware_20access',['xLowLayer Hardware Access',['../group__x_low_layer___hardware___access.html',1,'']]],
  ['xlowlayer_20interrupt_20assignments',['xLowLayer Interrupt Assignments',['../group__x_low_layer___interrupt___assignments.html',1,'']]],
  ['xlowlayer_20peripheral_20memmap',['xLowLayer Peripheral Memmap',['../group__x_low_layer___peripheral___memmap.html',1,'']]],
  ['xpwm',['XPWM',['../group__x_p_w_m.html',1,'']]],
  ['xpwm_20channel',['xPWM Channel',['../group__x_p_w_m___channel.html',1,'']]],
  ['xpwm_20configuration',['xPWM Configuration',['../group__x_p_w_m___config.html',1,'']]],
  ['xpwm_20event_20type',['xPWM Event Type',['../group__x_p_w_m___event___type.html',1,'']]],
  ['xpwm_20apis',['xPWM APIs',['../group__x_p_w_m___exported___a_p_is.html',1,'']]],
  ['xpwm_20frequency_20configure',['xPWM Frequency Configure',['../group__x_p_w_m___freq___config.html',1,'']]],
  ['xpwm_20interrupt_20type',['xPWM Interrupt Type',['../group__x_p_w_m___int___type.html',1,'']]],
  ['xrtc',['XRTC',['../group__x_r_t_c.html',1,'']]],
  ['xrtc_20day_20week',['xRTC Day Week',['../group__x_r_t_c___day___week.html',1,'']]],
  ['xrtc_20api',['xRTC API',['../group__x_r_t_c___exported___a_p_is.html',1,'']]],
  ['xrtc_20exported_20types',['xRTC Exported Types',['../group__x_r_t_c___exported___types.html',1,'']]],
  ['xrtc_20interrupt_20event',['xRTC Interrupt Event',['../group__x_r_t_c___i_n_t___event.html',1,'']]],
  ['xrtc_20interrupt_20type',['xRTC Interrupt Type',['../group__x_r_t_c___i_n_t___type.html',1,'']]],
  ['xrtc_20time_20type',['xRTC Time Type',['../group__x_r_t_c___time___type.html',1,'']]],
  ['xrtc_20year_20offset',['xRTC Year Offset',['../group__x_r_t_c___year___offset.html',1,'']]],
  ['xspi',['XSPI',['../group__x_s_p_i.html',1,'']]],
  ['xspi_20configure',['xSPI Configure',['../group__x_s_p_i___config.html',1,'']]],
  ['xspi_20dma',['xSPI DMA',['../group__x_s_p_i___d_m_a.html',1,'']]],
  ['xspi_20api',['xSPI API',['../group__x_s_p_i___exported___a_p_is.html',1,'']]],
  ['xspi_20interrupts',['xSPI Interrupts',['../group__x_s_p_i___ints.html',1,'']]],
  ['xspi_20interrupt_20event',['xSPI Interrupt Event',['../group__x_s_p_i___ints___event.html',1,'']]],
  ['xspi_20slave_20select',['xSPI Slave Select',['../group__x_s_p_i___slave_sel.html',1,'']]],
  ['xspi_20slave_20select_20mode',['xSPI Slave Select Mode',['../group__x_s_p_i___slave_sel_mode.html',1,'']]],
  ['xsysctl',['XSysCtl',['../group__x_sys_ctl.html',1,'']]],
  ['xsysctl_20clock_20set_20configuration',['xSysCtl Clock Set Configuration',['../group__x_sys_ctl___clock___set___config.html',1,'']]],
  ['xsysctl_20api',['xSysCtl API',['../group__x_sys_ctl___exported___a_p_is.html',1,'']]],
  ['xsysctl_20peripheral_20id',['xSysCtl Peripheral ID',['../group__x_sys_ctl___peripheral___i_d.html',1,'']]],
  ['xtimer',['XTIMER',['../group__x_t_i_m_e_r.html',1,'']]],
  ['xtimer_20capture_20edge_20type',['xTIMER Capture Edge Type',['../group__x_t_i_m_e_r___capture___edge___type.html',1,'']]],
  ['xtimer_20capture_20mode_20type',['xTIMER Capture Mode Type',['../group__x_t_i_m_e_r___capture___mode___type.html',1,'']]],
  ['xtimer_20count_20channel',['xTIMER Count Channel',['../group__x_t_i_m_e_r___count___channel.html',1,'']]],
  ['xtimer_20count_20direction',['xTIMER Count Direction',['../group__x_t_i_m_e_r___count___direction.html',1,'']]],
  ['xtimer_20counter_20phase_20type',['xTIMER Counter Phase Type',['../group__x_t_i_m_e_r___counter___phase___type.html',1,'']]],
  ['xtimer_20api',['xTIMER API',['../group__x_t_i_m_e_r___exported___a_p_is.html',1,'']]],
  ['xtimer_20interrupt_20event',['xTIMER Interrupt Event',['../group__x_t_i_m_e_r___i_n_t___event.html',1,'']]],
  ['xtimer_20interrupt',['xTIMER Interrupt',['../group__x_t_i_m_e_r___i_n_t___type.html',1,'']]],
  ['xtimer_20mode_20type',['xTIMER Mode Type',['../group__x_t_i_m_e_r___mode___type.html',1,'']]],
  ['xuart',['XUART',['../group__x_u_a_r_t.html',1,'']]],
  ['xuart_20enable_20blocks',['xUART Enable Blocks',['../group__x_u_a_r_t___enable___blocks.html',1,'']]],
  ['xuart_20error',['xUART Error',['../group__x_u_a_r_t___error.html',1,'']]],
  ['xuart_20event_20flags',['xUART Event Flags',['../group__x_u_a_r_t___event___flag.html',1,'']]],
  ['xuart_20api',['xUART API',['../group__x_u_a_r_t___exported___a_p_is.html',1,'']]],
  ['xuart_20fifo_20rx_20tiggle_20level',['xUART FIFO Rx Tiggle Level',['../group__x_u_a_r_t___f_i_f_o___rx___tiggle___level.html',1,'']]],
  ['xuart_20frame_20configuration',['xUART Frame Configuration',['../group__x_u_a_r_t___frame___configs.html',1,'']]],
  ['xuart_20interrupt',['xUART Interrupt',['../group__x_u_a_r_t___ints.html',1,'']]],
  ['xwdt',['XWDT',['../group__x_w_d_t.html',1,'']]],
  ['xwdt_20clock_20configuration',['xWDT Clock Configuration',['../group__x_w_d_t___clock___config.html',1,'']]],
  ['xwdt_20api',['xWDT API',['../group__x_w_d_t___exported___a_p_is.html',1,'']]],
  ['xwdt_20function_20type',['xWDT Function Type',['../group__x_w_d_t___function___type.html',1,'']]]
];
